<?php
/**
 * Global source catalog for Editorial News Importer Global.
 * Numeric fields: key, name, feed, site, region, country, language, type, legal, mode, active, max_items.
 */
defined('ABSPATH') || exit;

return [
    // Romania and owned sources.
    ['liga-sportivilor','Liga Sportivilor','https://ligasportivilor.ro/feed/','https://ligasportivilor.ro/','Romania','Romania','ro','owned','owned','summary_link',1,3],
    ['marian-mario','Marian Mario','https://marianmario.ro/feed/','https://marianmario.ro/','Romania','Romania','ro','owned','owned','summary_link',1,3],
    ['hotnews-ro','HotNews','https://hotnews.ro/feed','https://hotnews.ro/','Romania','Romania','ro','publisher','headline_link','title_link',1,1],
    ['g4media-ro','G4Media','https://www.g4media.ro/feed','https://www.g4media.ro/','Romania','Romania','ro','publisher','headline_link','title_link',1,1],
    ['economedia-ro','Economedia','https://economedia.ro/feed','https://economedia.ro/','Romania','Romania','ro','publisher','headline_link','title_link',1,1],
    ['pressone-ro','PressOne','https://pressone.ro/feed','https://pressone.ro/','Romania','Romania','ro','publisher','headline_link','title_link',1,1],
    ['recorder-ro','Recorder','https://recorder.ro/feed/','https://recorder.ro/','Romania','Romania','ro','publisher','headline_link','title_link',1,1],
    ['romania-insider','Romania Insider','https://www.romania-insider.com/rss.xml','https://www.romania-insider.com/','Europe','Romania','en','publisher','headline_link','title_link',1,1],
    ['news-ro','News.ro','https://www.news.ro/rss','https://www.news.ro/','Romania','Romania','ro','agency','headline_link','title_link',1,1],

    // United Nations and international public institutions.
    ['un-news-en','UN News - English','https://news.un.org/feed/subscribe/en/news/all/rss.xml','https://news.un.org/en/','Global','United Nations','en','institution','public_information','summary_link',1,2],
    ['un-news-fr','UN News - French','https://news.un.org/feed/subscribe/fr/news/all/rss.xml','https://news.un.org/fr/','Global','United Nations','fr','institution','public_information','summary_link',1,1],
    ['un-news-es','UN News - Spanish','https://news.un.org/feed/subscribe/es/news/all/rss.xml','https://news.un.org/es/','Global','United Nations','es','institution','public_information','summary_link',1,1],
    ['un-news-ar','UN News - Arabic','https://news.un.org/feed/subscribe/ar/news/all/rss.xml','https://news.un.org/ar/','Global','United Nations','ar','institution','public_information','summary_link',1,1],
    ['un-news-zh','UN News - Chinese','https://news.un.org/feed/subscribe/zh/news/all/rss.xml','https://news.un.org/zh/','Global','United Nations','zh','institution','public_information','summary_link',1,1],
    ['un-news-ru','UN News - Russian','https://news.un.org/feed/subscribe/ru/news/all/rss.xml','https://news.un.org/ru/','Global','United Nations','ru','institution','public_information','summary_link',1,1],
    ['un-news-pt','UN News - Portuguese','https://news.un.org/feed/subscribe/pt/news/all/rss.xml','https://news.un.org/pt/','Global','United Nations','pt','institution','public_information','summary_link',1,1],
    ['un-news-sw','UN News - Kiswahili','https://news.un.org/feed/subscribe/sw/news/all/rss.xml','https://news.un.org/sw/','Global','United Nations','sw','institution','public_information','summary_link',1,1],
    ['who-news','World Health Organization','https://www.who.int/rss-feeds/news-english.xml','https://www.who.int/news/','Global','United Nations','en','institution','public_information','summary_link',1,2],
    ['reliefweb-updates','ReliefWeb - Updates','https://reliefweb.int/updates/rss.xml','https://reliefweb.int/updates','Global','United Nations','en','institution','public_information','summary_link',1,2],
    ['wfp-stories','World Food Programme','https://www.wfp.org/rss.xml','https://www.wfp.org/stories','Global','United Nations','en','institution','public_information','summary_link',1,1],
    ['unicef-press','UNICEF Press Releases','https://www.unicef.org/press-releases/rss.xml','https://www.unicef.org/press-releases','Global','United Nations','en','institution','public_information','summary_link',1,1],
    ['unhcr-news','UNHCR News','https://www.unhcr.org/rss.xml','https://www.unhcr.org/news','Global','United Nations','en','institution','public_information','summary_link',1,1],
    ['unep-news','UN Environment Programme','https://www.unep.org/rss.xml','https://www.unep.org/news-and-stories','Global','United Nations','en','institution','public_information','summary_link',1,1],
    ['undp-news','UN Development Programme','https://www.undp.org/rss.xml','https://www.undp.org/news-centre','Global','United Nations','en','institution','public_information','summary_link',1,1],
    ['iom-news','International Organization for Migration','https://www.iom.int/rss.xml','https://www.iom.int/news','Global','United Nations','en','institution','public_information','summary_link',1,1],
    ['unesco-news','UNESCO','https://www.unesco.org/en/rss.xml','https://www.unesco.org/en/news','Global','United Nations','en','institution','public_information','summary_link',1,1],
    ['global-voices','Global Voices','https://globalvoices.org/feed/','https://globalvoices.org/','Global','International','en','nonprofit','open','summary_link',1,2],
    ['ips-news','Inter Press Service','https://www.ipsnews.net/feed/','https://www.ipsnews.net/','Global','International','en','nonprofit','headline_link','title_link',1,1],
    ['rsf-global','Reporters Without Borders - Global','https://rsf.org/en/rss','https://rsf.org/en','Global','International','en','nonprofit','public_information','summary_link',1,1],
    ['bellingcat','Bellingcat','https://www.bellingcat.com/feed/','https://www.bellingcat.com/','Global','International','en','nonprofit','headline_link','title_link',1,1],
    ['open-democracy','openDemocracy','https://www.opendemocracy.net/en/feed/','https://www.opendemocracy.net/','Global','International','en','nonprofit','headline_link','title_link',1,1],

    // Europe and European institutions.
    ['ec-presscorner','European Commission - Press Corner','https://ec.europa.eu/commission/presscorner/api/rss?language=en','https://ec.europa.eu/commission/presscorner/home/en','Europe','European Union','en','institution','public_information','summary_link',1,2],
    ['europarl-top','European Parliament - Top Stories','https://www.europarl.europa.eu/rss/doc/top-stories/en.xml','https://www.europarl.europa.eu/news/en','Europe','European Union','en','institution','public_information','summary_link',1,1],
    ['eu-council-press','Council of the EU - Press Releases','https://www.consilium.europa.eu/en/press/press-releases/rss/','https://www.consilium.europa.eu/en/press/press-releases/','Europe','European Union','en','institution','public_information','summary_link',1,1],
    ['ecb-press','European Central Bank - Press Releases','https://www.ecb.europa.eu/rss/press.html','https://www.ecb.europa.eu/press/html/index.en.html','Europe','European Union','en','institution','public_information','summary_link',1,1],
    ['eurostat-news','Eurostat - News Releases','https://ec.europa.eu/eurostat/rss/news-release.xml','https://ec.europa.eu/eurostat/web/main/news/news-releases','Europe','European Union','en','institution','public_information','summary_link',1,1],
    ['nato-news','NATO News','https://www.nato.int/cps/en/natohq/news_rss.htm','https://www.nato.int/cps/en/natohq/news.htm','Europe','NATO','en','institution','attribution','summary_link',1,1],
    ['euronews','Euronews','https://www.euronews.com/rss?level=theme&name=news','https://www.euronews.com/','Europe','Europe','en','publisher','headline_link','title_link',1,1],
    ['france24-en','France 24 - English','https://www.france24.com/en/rss','https://www.france24.com/en/','Europe','France','en','public_broadcaster','headline_link','title_link',1,1],
    ['dw-en','Deutsche Welle - English','https://rss.dw.com/rdf/rss-en-all','https://www.dw.com/en/','Europe','Germany','en','public_broadcaster','headline_link','title_link',1,1],
    ['politico-eu','POLITICO Europe','https://www.politico.eu/feed/','https://www.politico.eu/','Europe','European Union','en','publisher','headline_link','title_link',1,1],
    ['euractiv','Euractiv','https://www.euractiv.com/feed/','https://www.euractiv.com/','Europe','European Union','en','publisher','headline_link','title_link',1,1],
    ['euobserver','EUobserver','https://euobserver.com/rss','https://euobserver.com/','Europe','European Union','en','publisher','headline_link','title_link',1,1],
    ['balkan-insight','Balkan Insight','https://balkaninsight.com/feed/','https://balkaninsight.com/','Europe','Balkans','en','nonprofit','headline_link','title_link',1,1],
    ['kyiv-independent','The Kyiv Independent','https://kyivindependent.com/feed/','https://kyivindependent.com/','Europe','Ukraine','en','publisher','headline_link','title_link',1,1],
    ['swissinfo-en','SWI swissinfo.ch - English','https://www.swissinfo.ch/eng/rss','https://www.swissinfo.ch/eng/','Europe','Switzerland','en','public_broadcaster','headline_link','title_link',1,1],
    ['rte-news','RTE News','https://www.rte.ie/feeds/rss/?index=/news/','https://www.rte.ie/news/','Europe','Ireland','en','public_broadcaster','headline_link','title_link',1,1],
    ['thejournal-ie','TheJournal.ie','https://www.thejournal.ie/feed/','https://www.thejournal.ie/','Europe','Ireland','en','publisher','headline_link','title_link',1,1],
    ['sky-world','Sky News - World','https://feeds.skynews.com/feeds/rss/world.xml','https://news.sky.com/world','Europe','United Kingdom','en','publisher','headline_link','title_link',1,1],
    ['bbc-world','BBC News - World','https://feeds.bbci.co.uk/news/world/rss.xml','https://www.bbc.com/news/world','Europe','United Kingdom','en','public_broadcaster','headline_link','title_link',1,1],
    ['bbc-business','BBC News - Business','https://feeds.bbci.co.uk/news/business/rss.xml','https://www.bbc.com/news/business','Europe','United Kingdom','en','public_broadcaster','headline_link','title_link',1,1],
    ['bbc-tech','BBC News - Technology','https://feeds.bbci.co.uk/news/technology/rss.xml','https://www.bbc.com/news/technology','Europe','United Kingdom','en','public_broadcaster','headline_link','title_link',1,1],
    ['bbc-science','BBC News - Science and Environment','https://feeds.bbci.co.uk/news/science_and_environment/rss.xml','https://www.bbc.com/news/science_and_environment','Europe','United Kingdom','en','public_broadcaster','headline_link','title_link',1,1],
    ['bbc-health','BBC News - Health','https://feeds.bbci.co.uk/news/health/rss.xml','https://www.bbc.com/news/health','Europe','United Kingdom','en','public_broadcaster','headline_link','title_link',1,1],
    ['ekathimerini','Ekathimerini','https://www.ekathimerini.com/feed/','https://www.ekathimerini.com/','Europe','Greece','en','publisher','headline_link','title_link',1,1],
    ['err-estonia','ERR News - English','https://news.err.ee/rss','https://news.err.ee/','Europe','Estonia','en','public_broadcaster','headline_link','title_link',1,1],
    ['lrt-english','LRT English','https://www.lrt.lt/en/news-in-english?rss','https://www.lrt.lt/en/news-in-english','Europe','Lithuania','en','public_broadcaster','headline_link','title_link',1,1],
    ['lsm-english','LSM English','https://eng.lsm.lv/rss/','https://eng.lsm.lv/','Europe','Latvia','en','public_broadcaster','headline_link','title_link',1,1],
    ['notes-poland','Notes from Poland','https://notesfrompoland.com/feed/','https://notesfrompoland.com/','Europe','Poland','en','publisher','headline_link','title_link',1,1],
    ['brussels-times','The Brussels Times','https://www.brusselstimes.com/feed','https://www.brusselstimes.com/','Europe','Belgium','en','publisher','headline_link','title_link',1,1],
    ['dutchnews','DutchNews.nl','https://www.dutchnews.nl/feed/','https://www.dutchnews.nl/','Europe','Netherlands','en','publisher','headline_link','title_link',1,1],
    ['portugal-news','The Portugal News','https://www.theportugalnews.com/rss','https://www.theportugalnews.com/','Europe','Portugal','en','publisher','headline_link','title_link',1,1],
    ['ansa-english','ANSA - English','https://www.ansa.it/english/news/general_news/general_news_rss.xml','https://www.ansa.it/english/','Europe','Italy','en','agency','headline_link','title_link',1,1],
    ['iceland-review','Iceland Review','https://www.icelandreview.com/feed/','https://www.icelandreview.com/','Europe','Iceland','en','publisher','headline_link','title_link',1,1],
    ['news-in-english-no','News in English Norway','https://www.newsinenglish.no/feed/','https://www.newsinenglish.no/','Europe','Norway','en','publisher','headline_link','title_link',1,1],
    ['emerging-europe','Emerging Europe','https://emerging-europe.com/feed/','https://emerging-europe.com/','Europe','Europe','en','publisher','headline_link','title_link',1,1],

    // North America.
    ['cbc-top','CBC News - Top Stories','https://www.cbc.ca/cmlink/rss-topstories','https://www.cbc.ca/news','North America','Canada','en','public_broadcaster','headline_link','title_link',1,1],
    ['global-news-ca','Global News Canada','https://globalnews.ca/feed/','https://globalnews.ca/','North America','Canada','en','publisher','headline_link','title_link',1,1],
    ['abc-news-us','ABC News - Top Stories','https://abcnews.go.com/abcnews/topstories','https://abcnews.go.com/','North America','United States','en','publisher','headline_link','title_link',1,1],
    ['cbs-news-us','CBS News - Latest','https://www.cbsnews.com/latest/rss/main','https://www.cbsnews.com/latest/','North America','United States','en','publisher','headline_link','title_link',1,1],
    ['nbc-news-us','NBC News','https://feeds.nbcnews.com/nbcnews/public/news','https://www.nbcnews.com/','North America','United States','en','publisher','headline_link','title_link',1,1],
    ['pbs-newshour','PBS NewsHour','https://www.pbs.org/newshour/feeds/rss/headlines','https://www.pbs.org/newshour/','North America','United States','en','public_broadcaster','headline_link','title_link',1,1],
    ['npr-news','NPR News','https://feeds.npr.org/1001/rss.xml','https://www.npr.org/sections/news/','North America','United States','en','public_broadcaster','headline_link','title_link',1,1],
    ['npr-world','NPR World','https://feeds.npr.org/1004/rss.xml','https://www.npr.org/sections/world/','North America','United States','en','public_broadcaster','headline_link','title_link',1,1],
    ['npr-politics','NPR Politics','https://feeds.npr.org/1014/rss.xml','https://www.npr.org/sections/politics/','North America','United States','en','public_broadcaster','headline_link','title_link',1,1],
    ['propublica','ProPublica','https://www.propublica.org/feeds/propublica/main','https://www.propublica.org/','North America','United States','en','nonprofit','headline_link','title_link',1,1],
    ['democracy-now','Democracy Now!','https://www.democracynow.org/democracynow.rss','https://www.democracynow.org/','North America','United States','en','nonprofit','headline_link','title_link',1,1],
    ['the-hill','The Hill','https://thehill.com/feed/','https://thehill.com/','North America','United States','en','publisher','headline_link','title_link',1,1],
    ['politico-us','POLITICO - US','https://www.politico.com/rss/politicopicks.xml','https://www.politico.com/','North America','United States','en','publisher','headline_link','title_link',1,1],
    ['csmonitor','The Christian Science Monitor','https://rss.csmonitor.com/feeds/all','https://www.csmonitor.com/','North America','United States','en','publisher','headline_link','title_link',1,1],
    ['nasa-releases','NASA News Releases','https://www.nasa.gov/news-release/feed/','https://www.nasa.gov/news-release/','North America','United States','en','government','public_domain','summary_link',1,2],
    ['nasa-earth','NASA Earth Science','https://science.nasa.gov/earth/feed/','https://science.nasa.gov/earth/','North America','United States','en','government','public_domain','summary_link',1,1],
    ['nih-releases','US National Institutes of Health','https://www.nih.gov/news-events/news-releases/rss.xml','https://www.nih.gov/news-events/news-releases','North America','United States','en','government','public_domain','summary_link',1,1],
    ['usgs-news','US Geological Survey - News','https://www.usgs.gov/news/all-news-items/rss.xml','https://www.usgs.gov/news','North America','United States','en','government','public_domain','summary_link',1,1],
    ['sec-releases','US SEC - Press Releases','https://www.sec.gov/news/pressreleases.rss','https://www.sec.gov/newsroom/press-releases','North America','United States','en','government','public_domain','summary_link',1,1],
    ['ftc-releases','US FTC - Press Releases','https://www.ftc.gov/feeds/press-release.xml','https://www.ftc.gov/news-events/news/press-releases','North America','United States','en','government','public_domain','summary_link',1,1],
    ['doj-releases','US Department of Justice','https://www.justice.gov/feeds/opa/justice-news.xml','https://www.justice.gov/news','North America','United States','en','government','public_domain','summary_link',1,1],
    ['eia-energy','US EIA - Today in Energy','https://www.eia.gov/todayinenergy/rss.php','https://www.eia.gov/todayinenergy/','North America','United States','en','government','public_domain','summary_link',1,1],

    // Latin America and Caribbean.
    ['agencia-brasil','Agencia Brasil','https://agenciabrasil.ebc.com.br/rss/ultimasnoticias/feed.xml','https://agenciabrasil.ebc.com.br/','Latin America','Brazil','pt','public_broadcaster','headline_link','title_link',1,1],
    ['buenos-aires-times','Buenos Aires Times','https://www.batimes.com.ar/feed','https://www.batimes.com.ar/','Latin America','Argentina','en','publisher','headline_link','title_link',1,1],
    ['mercopress','MercoPress','https://en.mercopress.com/rss','https://en.mercopress.com/','Latin America','Uruguay','en','publisher','headline_link','title_link',1,1],
    ['mexico-news-daily','Mexico News Daily','https://mexiconewsdaily.com/feed/','https://mexiconewsdaily.com/','Latin America','Mexico','en','publisher','headline_link','title_link',1,1],
    ['latin-america-reports','Latin America Reports','https://latinamericareports.com/feed/','https://latinamericareports.com/','Latin America','Latin America','en','publisher','headline_link','title_link',1,1],
    ['tico-times','The Tico Times','https://ticotimes.net/feed','https://ticotimes.net/','Latin America','Costa Rica','en','publisher','headline_link','title_link',1,1],
    ['jamaica-gleaner','Jamaica Gleaner','https://jamaica-gleaner.com/feed','https://jamaica-gleaner.com/','Latin America','Jamaica','en','publisher','headline_link','title_link',1,1],
    ['caribbean-weekly','Caribbean National Weekly','https://www.caribbeannationalweekly.com/feed/','https://www.caribbeannationalweekly.com/','Latin America','Caribbean','en','publisher','headline_link','title_link',1,1],

    // Africa.
    ['africanews','Africanews','https://www.africanews.com/feed/','https://www.africanews.com/','Africa','Africa','en','publisher','headline_link','title_link',1,1],
    ['daily-maverick','Daily Maverick','https://www.dailymaverick.co.za/dmrss/','https://www.dailymaverick.co.za/','Africa','South Africa','en','publisher','headline_link','title_link',1,1],
    ['mail-guardian','Mail & Guardian','https://mg.co.za/feed/','https://mg.co.za/','Africa','South Africa','en','publisher','headline_link','title_link',1,1],
    ['premium-times','Premium Times Nigeria','https://www.premiumtimesng.com/feed','https://www.premiumtimesng.com/','Africa','Nigeria','en','publisher','headline_link','title_link',1,1],
    ['the-cable-ng','TheCable Nigeria','https://www.thecable.ng/feed','https://www.thecable.ng/','Africa','Nigeria','en','publisher','headline_link','title_link',1,1],
    ['ghanaweb-news','GhanaWeb News','https://www.ghanaweb.com/GhanaHomePage/rss/news.xml','https://www.ghanaweb.com/GhanaHomePage/NewsArchive/','Africa','Ghana','en','publisher','headline_link','title_link',1,1],
    ['new-times-rwanda','The New Times Rwanda','https://www.newtimes.co.rw/feed','https://www.newtimes.co.rw/','Africa','Rwanda','en','publisher','headline_link','title_link',1,1],
    ['namibian','The Namibian','https://www.namibian.com.na/feed/','https://www.namibian.com.na/','Africa','Namibia','en','publisher','headline_link','title_link',1,1],
    ['morocco-world-news','Morocco World News','https://www.moroccoworldnews.com/feed','https://www.moroccoworldnews.com/','Africa','Morocco','en','publisher','headline_link','title_link',1,1],
    ['egypt-independent','Egypt Independent','https://egyptindependent.com/feed/','https://egyptindependent.com/','Africa','Egypt','en','publisher','headline_link','title_link',1,1],

    // Middle East.
    ['al-jazeera-en','Al Jazeera English','https://www.aljazeera.com/xml/rss/all.xml','https://www.aljazeera.com/','Middle East','Qatar','en','publisher','headline_link','title_link',1,1],
    ['arab-news','Arab News','https://www.arabnews.com/rss.xml','https://www.arabnews.com/','Middle East','Saudi Arabia','en','publisher','headline_link','title_link',1,1],
    ['times-israel','The Times of Israel','https://www.timesofisrael.com/feed/','https://www.timesofisrael.com/','Middle East','Israel','en','publisher','headline_link','title_link',1,1],
    ['jerusalem-post','The Jerusalem Post','https://www.jpost.com/rss/rssfeedsfrontpage.aspx','https://www.jpost.com/','Middle East','Israel','en','publisher','headline_link','title_link',1,1],
    ['middle-east-monitor','Middle East Monitor','https://www.middleeastmonitor.com/feed/','https://www.middleeastmonitor.com/','Middle East','United Kingdom','en','publisher','headline_link','title_link',1,1],
    ['iran-international','Iran International - English','https://www.iranintl.com/en/feed','https://www.iranintl.com/en','Middle East','Iran','en','publisher','headline_link','title_link',1,1],
    ['national-uae','The National - UAE','https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml','https://www.thenationalnews.com/','Middle East','United Arab Emirates','en','publisher','headline_link','title_link',1,1],
    ['lorient-today','L\'Orient Today','https://today.lorientlejour.com/rss','https://today.lorientlejour.com/','Middle East','Lebanon','en','publisher','headline_link','title_link',1,1],

    // Asia.
    ['the-hindu','The Hindu','https://www.thehindu.com/feeder/default.rss','https://www.thehindu.com/','Asia','India','en','publisher','headline_link','title_link',1,1],
    ['times-india','The Times of India - Top Stories','https://timesofindia.indiatimes.com/rssfeedstopstories.cms','https://timesofindia.indiatimes.com/','Asia','India','en','publisher','headline_link','title_link',1,1],
    ['indian-express','The Indian Express','https://indianexpress.com/feed/','https://indianexpress.com/','Asia','India','en','publisher','headline_link','title_link',1,1],
    ['ndtv-top','NDTV - Top Stories','https://feeds.feedburner.com/ndtvnews-top-stories','https://www.ndtv.com/','Asia','India','en','publisher','headline_link','title_link',1,1],
    ['dawn-pakistan','Dawn','https://www.dawn.com/feeds/home','https://www.dawn.com/','Asia','Pakistan','en','publisher','headline_link','title_link',1,1],
    ['kathmandu-post','The Kathmandu Post','https://kathmandupost.com/rss','https://kathmandupost.com/','Asia','Nepal','en','publisher','headline_link','title_link',1,1],
    ['dhaka-tribune','Dhaka Tribune','https://www.dhakatribune.com/feed','https://www.dhakatribune.com/','Asia','Bangladesh','en','publisher','headline_link','title_link',1,1],
    ['irrawaddy','The Irrawaddy','https://www.irrawaddy.com/feed','https://www.irrawaddy.com/','Asia','Myanmar','en','publisher','headline_link','title_link',1,1],
    ['bangkok-post','Bangkok Post - Top Stories','https://www.bangkokpost.com/rss/data/topstories.xml','https://www.bangkokpost.com/','Asia','Thailand','en','publisher','headline_link','title_link',1,1],
    ['vietnam-news','Viet Nam News','https://vietnamnews.vn/rss','https://vietnamnews.vn/','Asia','Vietnam','en','publisher','headline_link','title_link',1,1],
    ['antara-en','ANTARA News - English','https://en.antaranews.com/rss/news.xml','https://en.antaranews.com/','Asia','Indonesia','en','agency','headline_link','title_link',1,1],
    ['cna-top','Channel NewsAsia','https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml','https://www.channelnewsasia.com/','Asia','Singapore','en','publisher','headline_link','title_link',1,1],
    ['straits-world','The Straits Times - World','https://www.straitstimes.com/news/world/rss.xml','https://www.straitstimes.com/world','Asia','Singapore','en','publisher','headline_link','title_link',1,1],
    ['scmp-world','South China Morning Post - World','https://www.scmp.com/rss/91/feed','https://www.scmp.com/news/world','Asia','Hong Kong','en','publisher','headline_link','title_link',1,1],
    ['hong-kong-free-press','Hong Kong Free Press','https://hongkongfp.com/feed/','https://hongkongfp.com/','Asia','Hong Kong','en','nonprofit','headline_link','title_link',1,1],
    ['japan-times','The Japan Times','https://www.japantimes.co.jp/feed/','https://www.japantimes.co.jp/','Asia','Japan','en','publisher','headline_link','title_link',1,1],
    ['nhk-japan','NHK News - Japan','https://www3.nhk.or.jp/rss/news/cat0.xml','https://www3.nhk.or.jp/news/','Asia','Japan','ja','public_broadcaster','headline_link','title_link',1,1],
    ['korea-herald','The Korea Herald','https://www.koreaherald.com/rss/010000000000.xml','https://www.koreaherald.com/','Asia','South Korea','en','publisher','headline_link','title_link',1,1],
    ['taipei-times','Taipei Times','https://www.taipeitimes.com/xml/index.rss','https://www.taipeitimes.com/','Asia','Taiwan','en','publisher','headline_link','title_link',1,1],
    ['focus-taiwan','Focus Taiwan','https://focustaiwan.tw/rss','https://focustaiwan.tw/','Asia','Taiwan','en','agency','headline_link','title_link',1,1],
    ['inquirer-ph','Philippine Daily Inquirer','https://newsinfo.inquirer.net/feed','https://newsinfo.inquirer.net/','Asia','Philippines','en','publisher','headline_link','title_link',1,1],
    ['rappler','Rappler','https://www.rappler.com/feed/','https://www.rappler.com/','Asia','Philippines','en','publisher','headline_link','title_link',1,1],

    // Oceania.
    ['rnz-national','RNZ - New Zealand','https://www.rnz.co.nz/rss/national.xml','https://www.rnz.co.nz/news/national','Oceania','New Zealand','en','public_broadcaster','headline_link','title_link',1,1],
    ['rnz-world','RNZ - World','https://www.rnz.co.nz/rss/world.xml','https://www.rnz.co.nz/news/world','Oceania','New Zealand','en','public_broadcaster','headline_link','title_link',1,1],
    ['rnz-business','RNZ - Business','https://www.rnz.co.nz/rss/business.xml','https://www.rnz.co.nz/news/business','Oceania','New Zealand','en','public_broadcaster','headline_link','title_link',1,1],
    ['rnz-sport','RNZ - Sport','https://www.rnz.co.nz/rss/sport.xml','https://www.rnz.co.nz/news/sport','Oceania','New Zealand','en','public_broadcaster','headline_link','title_link',1,1],
    ['sbs-news','SBS News','https://www.sbs.com.au/news/feed','https://www.sbs.com.au/news/','Oceania','Australia','en','public_broadcaster','headline_link','title_link',1,1],
    ['conversation-au','The Conversation - Australia','https://theconversation.com/au/articles.atom','https://theconversation.com/au','Oceania','Australia','en','nonprofit','open','summary_link',1,1],
    ['newsroom-nz','Newsroom New Zealand','https://newsroom.co.nz/feed/','https://newsroom.co.nz/','Oceania','New Zealand','en','publisher','headline_link','title_link',1,1],
    ['fiji-times','The Fiji Times','https://www.fijitimes.com.fj/feed/','https://www.fijitimes.com.fj/','Oceania','Fiji','en','publisher','headline_link','title_link',1,1],

    // Science, climate, technology and sport.
    ['conversation-global','The Conversation - Global','https://theconversation.com/global/articles.atom','https://theconversation.com/global','Global','International','en','nonprofit','open','summary_link',1,2],
    ['mongabay','Mongabay','https://news.mongabay.com/feed/','https://news.mongabay.com/','Global','International','en','nonprofit','headline_link','title_link',1,1],
    ['carbon-brief','Carbon Brief','https://www.carbonbrief.org/feed/','https://www.carbonbrief.org/','Global','United Kingdom','en','nonprofit','headline_link','title_link',1,1],
    ['inside-climate','Inside Climate News','https://insideclimatenews.org/feed/','https://insideclimatenews.org/','North America','United States','en','nonprofit','headline_link','title_link',1,1],
    ['nature-news','Nature','https://www.nature.com/nature.rss','https://www.nature.com/','Global','International','en','science','headline_link','title_link',1,1],
    ['science-daily','ScienceDaily','https://www.sciencedaily.com/rss/all.xml','https://www.sciencedaily.com/','North America','United States','en','science','headline_link','title_link',1,1],
    ['phys-org','Phys.org','https://phys.org/rss-feed/','https://phys.org/','Global','International','en','science','headline_link','title_link',1,1],
    ['medical-xpress','Medical Xpress','https://medicalxpress.com/rss-feed/','https://medicalxpress.com/','Global','International','en','science','headline_link','title_link',1,1],
    ['space-com','Space.com','https://www.space.com/feeds/all','https://www.space.com/','North America','United States','en','science','headline_link','title_link',1,1],
    ['techcrunch','TechCrunch','https://techcrunch.com/feed/','https://techcrunch.com/','North America','United States','en','technology','headline_link','title_link',1,1],
    ['the-verge','The Verge','https://www.theverge.com/rss/index.xml','https://www.theverge.com/','North America','United States','en','technology','headline_link','title_link',1,1],
    ['ars-technica','Ars Technica','https://feeds.arstechnica.com/arstechnica/index','https://arstechnica.com/','North America','United States','en','technology','headline_link','title_link',1,1],
    ['wired','WIRED','https://www.wired.com/feed/rss','https://www.wired.com/','North America','United States','en','technology','headline_link','title_link',1,1],
    ['mit-tech-review','MIT Technology Review','https://www.technologyreview.com/feed/','https://www.technologyreview.com/','North America','United States','en','technology','headline_link','title_link',1,1],
    ['bbc-sport','BBC Sport','https://feeds.bbci.co.uk/sport/rss.xml?edition=uk','https://www.bbc.com/sport','Europe','United Kingdom','en','sport','headline_link','title_link',1,1],
    ['espn-top','ESPN - Top Headlines','https://www.espn.com/espn/rss/news','https://www.espn.com/','North America','United States','en','sport','headline_link','title_link',1,1],
    ['inside-games','Inside the Games','https://www.insidethegames.biz/rss','https://www.insidethegames.biz/','Global','International','en','sport','headline_link','title_link',1,1],
];
